# conda environment configuration for mybinder
name: mybinder-env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - gdal
  - pip
  - pip:
    - matplotlib
    - owslib
    - pandas
    - tabulate
